name: build_items_json
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build item parser
        run: |
          cd source
          chmod +x build.sh
          ./build.sh
          mv itemParser ..
          cd ..
      - name: Run item parser
        run: ./itemParser
      - name: Release new items' data
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest items data"
          files: |
            items.json
            splices.txt
            combines.txt
